name = "MyProject"
uuid = "9dc6d92e-b0f0-465f-9515-526c953e6b0f"
authors = ["ledv <ldvinh@yahoo.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
